nx: 100
ny: 100
hl: 10
hr: 5
damRadius: 10
maxDuration: 20
maxSteps: 10000
outputDelay: 1
setup: DamBreak2d
obstacleBathymetry: -15.1
obstacleX0: 3
obstacleX1: 35
obstacleY0: 10
obstacleY1: 90