setup: Tsunami2d
bathymetryFile: ../tohoku_gebco08_ucsb3_250m_bath.nc
displacementFile: ../tohoku_gebco08_ucsb3_250m_displ.nc
maxDuration: 3600
maxSteps: 100000
scale: 1
outputFile: tohoku-250.nc
outputStepSize: 12
outputPeriod: 3