setup: Tsunami2d
bathymetryFile: /beegfs/gi76tal/tohoku_gebco08_ucsb3_250m_bath.nc
displacementFile: /beegfs/gi76tal/tohoku_gebco08_ucsb3_250m_displ.nc
maxDuration: 300
maxSteps: 100000
scale: 1
outputFile: tohoku-250.nc
outputStepSize: 4
outputPeriod: 60
checkpointPeriod: 600
