setup: Tsunami2d
bathymetryFile: ../chile_gebco20_usgs_250m_bath.nc
displacementFile: ../chile_gebco20_usgs_250m_displ.nc
maxDuration: 10000
maxSteps: 100000
scale: 0.5
outputFile: chile-500-2.nc
outputStepSize: 6
outputPeriod: 25